name: Docker Image Build And Push

on:
  workflow_run:
    workflows: ["CI BuildWithTest"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anasalsarairah/profileme:$(date +%s)
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}
     
    - name: push to Docker hub 
      run: docker push -t anasalsarairah/profileme:$(date +%s)
     
    
