name: Docker Image Build And Push

on:
  workflow_run:
    workflows: ["CI BuildWithTest"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anasalsarairah/profileme:$(date +%s)


