name: Docker Image Build And Push

on:
  workflow_run:
    workflows: ["CI BuildWithTest"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Pump and Release
      id: release
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anasalsarairah/profileme:${{ steps.release.outputs.new_tag }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       registry: docker.io
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}
     
    - name: push to Docker hub 
      run: docker push anasalsarairah/profileme:latest anasalsarairah/profileme:${{ steps.release.outputs.new_tag }}
     
    
